<!-- http://code.vky.co.in/insert-data-custom-table-using-resource-model-magento-2/ -->
<form class="" action="<?php echo $block->getBaseUrl().'makanan/actiona/save'; ?>" id="create_makanan" method="post">
    <fieldset class="fieldset">
        <legend class="legend"><span>Buat Makanan</span></legend><br/>
        <p>Monggo dilengkapi datanya!</p>

        <div class="field nama">
            <label class="label" for="nama"><span>Nama</span></label>
            <div class="control">
                <input name="nama" id="nama" title="Nama" value="" class="input-text" type="text">
            </div>
        </div>

        <div class="field nama">
            <label class="label" for="penjelasan"><span>Penjelasan</span></label>
            <div class="control">
                <textarea name="penjelasan" id="penjelasan" title="Penjelasan" value="" class="input-text" type="text"></textarea>
            </div>
        </div>

    </fieldset>

    <div class="actions-toolbar">
        <div class="primary">
            <button type="submit" title="Submit" class="action submit primary">
                <span>Submit</span>
            </button>
        </div>
    </div>
</form>