<?php /** @var Toptal\Blog\Block\Posts $block */ ?>

<h1>Best Foods</h1>

<a href="/makanan/actiona/create" class="btn btn-success">Buat Baru</a>

<br/>
&nbsp;

<ul>
<?php foreach($block->getFoods() as $k=>$food): ?>

    <li>
        <?php echo $food->getNama(); ?> 
        (
            <a href="/makanan/detail/detail/id/<?php echo $food->getId(); ?>"> View </a>
            <a href="/makanan/actiona/create/id/<?php echo $food->getId(); ?>"> Edit </a>
        )
        <form action="<?php echo $block->getBaseUrl()?>makanan/actiona/save/id/<?php echo $food->getId(); ?>" method="post" id="delete_form<?php echo $k; ?>">
            <input type="hidden" name="_method" value="delete" />
            <input type="hidden" name="form_key" />
            <input type="hidden" name="makanan_id" id="makanan_id" title="makanan_id" value="<?php echo $food->getId(); ?>" />

            <a href="javascript:{}" onclick="document.getElementById('delete_form<?php echo $k; ?>').submit(); return false" >Delete</a>
        </form>
         
    </li>

<?php endforeach; ?>
</ul>

<?php if ($block->getPagerHtml()): ?>
    <div class="order-products-toolbar toolbar bottom"><?php echo $block->getPagerHtml(); ?></div>
<?php endif ?>