<div style="float: left;width:100%; background-color: #6a7175" >

    <div style="float: left;width:30%;">
        <h5>Categories</h5>

        Lorema ipsuma dolore site amete
    </div>

    <div style="float: left;width:30%;margin-left:15px;">
        <h5>Categories</h5>

        Lorema ipsuma dolore site amete
    </div>

    <div style="float: right;width:30%;">
        <h5>Categories</h5>

        Lorema ipsuma dolore site amete
    </div>

</div>