<div class="widget block block-static-block">
    <a href="http://demo-acm-2.bird.eu/collections/yoga-new.html" class="block-promo home-main" style="width: 68%; float: left;">
        <img src="http://demo-acm-2.bird.eu/pub/media/wysiwyg/home/home-main.jpg" alt="" >
        <span class="content" style="left:10px;">
            <strong class="title">Lprem ipsum dolor!</strong>
            <span class="info">Follow us on facebook!</span>

            <img src="https://akrilikexpress.com/file/2017/10/button-view-more.png" style="width:50%;" />
        </span>
    </a>

    <a href="http://demo-acm-2.bird.eu/promotions/pants-all.html" class="block-promo home-pants" style="width: 30%; float: right; height: 450px">
        <img src="http://demo-acm-2.bird.eu/pub/media/wysiwyg/home/home-pants.jpg" alt="">
        <span class="content">
               <strong class="title">Follow us!</strong>
               <span class="info">Follow us on facebook!</span>
               <img src="https://novacapsfans.files.wordpress.com/2015/08/like.jpg" style="width:50%;" />
        </span>
    </a>
</div>