<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php
/**
 * Top menu for store
 *
 * @var $block \Magento\Theme\Block\Html\Topmenu
 */
?>
<?php $columnsLimit = $block->getColumnsLimit() ?: 0; ?>
<?php $_menu = $block->getHtml('level-top', 'submenu', $columnsLimit) ?>

<nav class="navigation" data-action="navigation" style="text-align:right; background-color:white;">
    <ul data-mage-init='{"menu":{"responsive":true, "expanded":true, "position":{"my":"left top","at":"left bottom"}}}'>
        <li class="level0 nav-4 category-item level-top parent ui-menu-item" role="presentation">
            <a href="http://tokoku.local/gear.html" class="level-top ui-corner-all" aria-haspopup="true" id="ui-id-5" tabindex="-1" role="menuitem">
                <span class="ui-menu-icon ui-icon ui-icon-carat-1-e"></span><span>Gear</span>
            </a>

            <ul class="level0 submenu ui-menu ui-widget ui-widget-content ui-corner-all" role="menu" aria-expanded="false" style="display: none; top: 53px; left: -0.15625px;" aria-hidden="true">
                <li class="level1 nav-4-1 category-item first ui-menu-item" role="presentation">
                    <a href="http://tokoku.local/gear/bags.html" id="ui-id-24" class="ui-corner-all" tabindex="-1" role="menuitem"><span>Bags</span></a>
                </li>
                <li class="level1 nav-4-2 category-item ui-menu-item" role="presentation"><a href="http://tokoku.local/gear/fitness-equipment.html" id="ui-id-25" class="ui-corner-all" tabindex="-1" role="menuitem"><span>Fitness Equipment</span></a></li><li class="level1 nav-4-3 category-item last ui-menu-item" role="presentation">
                    <a href="http://tokoku.local/gear/watches.html" id="ui-id-26" class="ui-corner-all" tabindex="-1" role="menuitem"><span>Watches</span></a>
                </li>
            </ul>

        </li>

        <li class="level0 nav-6 category-item last level-top ui-menu-item" role="presentation"><a href="http://tokoku.local/sale.html" class="level-top ui-corner-all" id="ui-id-7" tabindex="-1" role="menuitem">
            <span>About</span></a>
        </li>

        <li class="level0 nav-6 category-item last level-top ui-menu-item" role="presentation"><a href="http://tokoku.local/sale.html" class="level-top ui-corner-all" id="ui-id-7" tabindex="-1" role="menuitem">
            <span>Contact</span></a>
        </li>


        <li class="level0 nav-4 category-item level-top parent ui-menu-item" role="presentation">
            <a href="http://tokoku.local/gear.html" class="level-top ui-corner-all" aria-haspopup="true" id="ui-id-5" tabindex="-1" role="menuitem">
                <span class="ui-menu-icon ui-icon ui-icon-carat-1-e"></span><span>EN</span>
            </a>

            <ul class="level0 submenu ui-menu ui-widget ui-widget-content ui-corner-all" role="menu" aria-expanded="false" style="display: none; top: 53px; left: -0.15625px;" aria-hidden="true">
                <li class="level1 nav-4-1 category-item first ui-menu-item" role="presentation">
                    <a href="http://tokoku.local/gear/bags.html" id="ui-id-24" class="ui-corner-all" tabindex="-1" role="menuitem"><span>EN</span></a>
                </li>

                <li class="level1 nav-4-3 category-item last ui-menu-item" role="presentation">
                    <a href="http://tokoku.local/gear/watches.html" id="ui-id-26" class="ui-corner-all" tabindex="-1" role="menuitem"><span>EN</span></a>
                </li>
            </ul>

        </li>

        <li class="level0 nav-4 category-item level-top parent ui-menu-item" role="presentation">
            <a href="http://tokoku.local/gear.html" class="level-top ui-corner-all" aria-haspopup="true" id="ui-id-5" tabindex="-1" role="menuitem">
                <span class="ui-menu-icon ui-icon ui-icon-carat-1-e"></span><span>$US</span>
            </a>

            <ul class="level0 submenu ui-menu ui-widget ui-widget-content ui-corner-all" role="menu" aria-expanded="false" style="display: none; top: 53px; left: -0.15625px;" aria-hidden="true">
                <li class="level1 nav-4-1 category-item first ui-menu-item" role="presentation">
                    <a href="http://tokoku.local/gear/bags.html" id="ui-id-24" class="ui-corner-all" tabindex="-1" role="menuitem"><span>$US</span></a>
                </li>

                <li class="level1 nav-4-3 category-item last ui-menu-item" role="presentation">
                    <a href="http://tokoku.local/gear/watches.html" id="ui-id-26" class="ui-corner-all" tabindex="-1" role="menuitem"><span>IDR</span></a>
                </li>
            </ul>

        </li>

        <li class="level0 nav-6 category-item last level-top ui-menu-item" role="presentation"><a href="http://tokoku.local/sale.html" class="level-top ui-corner-all" id="ui-id-7" tabindex="-1" role="menuitem">
            <span>🔎</span></a>
        </li>

        <li class="level0 nav-6 category-item last level-top ui-menu-item" role="presentation"><a href="http://tokoku.local/sale.html" class="level-top ui-corner-all" id="ui-id-7" tabindex="-1" role="menuitem">
            <span>👩</span></a>
        </li>

        <li class="level0 nav-6 category-item last level-top ui-menu-item" role="presentation"><a href="http://tokoku.local/sale.html" class="level-top ui-corner-all" id="ui-id-7" tabindex="-1" role="menuitem">
            <span>❤</span></a>
        </li>

        <li class="level0 nav-6 category-item last level-top ui-menu-item" role="presentation"><a href="http://tokoku.local/sale.html" class="level-top ui-corner-all" id="ui-id-7" tabindex="-1" role="menuitem">
            <span>✉</span></a>
        </li>

    </ul>

</nav>