FROM nginx:latest

COPY default.conf /etc/nginx/conf.d/
COPY astrntlocal.conf /etc/nginx/conf.d/
COPY appastrntlocal.conf /etc/nginx/conf.d/
COPY apiastrntlocal.conf /etc/nginx/conf.d/
COPY qna_astrntlocal.conf /etc/nginx/conf.d/
#COPY cake_php.conf /etc/nginx/conf.d/
COPY cakephp2.conf /etc/nginx/conf.d/
COPY cakephp3.conf /etc/nginx/conf.d/
COPY website_toolbox.conf /etc/nginx/conf.d/
COPY website_toolbox2.conf /etc/nginx/conf.d/
