FROM nginx:latest

COPY default.conf /etc/nginx/conf.d/
COPY astrntlocal.conf /etc/nginx/conf.d/
COPY appastrntlocal.conf /etc/nginx/conf.d/
COPY apiastrntlocal.conf /etc/nginx/conf.d/
COPY qna_astrntlocal.conf /etc/nginx/conf.d/
