FROM nginx:latest

COPY default.conf /etc/nginx/conf.d/
COPY myshop.conf /etc/nginx/conf.d/
COPY tokoku.conf /etc/nginx/conf.d/
COPY senheng.conf /etc/nginx/conf.d/
COPY tokoplas.conf /etc/nginx/conf.d/
