<?php

$objectManager =  \Magento\Framework\App\ObjectManager::getInstance(); 
$categoryCollection = $objectManager->get('\Magento\Catalog\Model\ResourceModel\Category\CollectionFactory');

$categoryHelper = $objectManager->get('\Magento\Catalog\Helper\Category');
$categories = $categoryHelper->getStoreCategories();

foreach ($categories as $category) { 
?>  
    <a href="<?php echo $category->getUrl();?>"><?php echo $category->getName() ;?></a>

<?php } ?>