<div style="">
    <strong id="block-related-heading" role="heading" aria-level="2">
        <h2 style="font-weight:bold;">Featured Brand &nbsp;</h2> 
    </strong>
    <hr />
    <img src="<?php echo $block->getViewFileUrl('images/brands/samsung.png');?>" style="max-width: 150px" /> &nbsp;
    <img src="<?php echo $block->getViewFileUrl('images/brands/apple.png');?>" style="max-height: 50px" /> &nbsp;
    <img src="<?php echo $block->getViewFileUrl('images/brands/phillips.png');?>" style="max-width: 150px" /> &nbsp;
    <img src="<?php echo $block->getViewFileUrl('images/brands/sony.png');?>" style="max-width: 150px" /> &nbsp;
    <img src="<?php echo $block->getViewFileUrl('images/brands/sharp.png');?>" style="max-width: 150px" /> &nbsp;
    <img src="<?php echo $block->getViewFileUrl('images/brands/honeywell.png');?>" style="max-width: 150px" /> &nbsp;
    <img src="<?php echo $block->getViewFileUrl('images/brands/panasonic.png');?>" style="max-width: 150px" /> &nbsp;
    <img src="<?php echo $block->getViewFileUrl('images/brands/toshiba.png');?>" style="max-width: 150px" /> &nbsp;
    <img src="<?php echo $block->getViewFileUrl('images/brands/microsoft.png');?>" style="max-width: 150px" /> &nbsp;

    <img src="<?php echo $block->getViewFileUrl('images/brands/elba.png');?>" style="max-width: 150px" /> &nbsp;
    <img src="<?php echo $block->getViewFileUrl('images/brands/lg.png');?>" style="max-width: 150px" /> &nbsp;
    <img src="<?php echo $block->getViewFileUrl('images/brands/faber.png');?>" style="max-width: 150px" /> &nbsp;
</div>