<?php 
    $_objectManager = \Magento\Framework\App\ObjectManager::getInstance();
    $imageHelper  = $_objectManager->get('\Magento\Catalog\Helper\Image');
?>

<div class="block related">

    <div class="block-title title">
        <strong id="block-related-heading" role="heading" aria-level="2">
            <h2 style="float:left;font-weight:bold;">Flash Sale &nbsp;</h2> 
            <h2 style="float:left">
                <span>01</span> : <span>01</span> : <span>02</span>
            </h2>

            <input type="button" value="VIEW MORE OFFER" class="button" style="float:right;margin-top:10px;"/>

        </strong>
        <hr style="clear:both"/>
    </div>

    <div class="block-content content" aria-labelledby="block-related-heading">
        <div class="products wrapper grid products-grid products-related">
            <ol class="products list items product-items">

                <?php foreach ($block->getFlashSaleProductCollection() as $product): ?>

                    <li class="item product product-item" style="">
                        <div class="product-item-info">
                            
                            <span style="float:right">50%</span>

                            <a href="<?= $product->getProductUrl() ?>" class="product photo product-item-photo">
                                <?php $image_url = $imageHelper->init($product, 'product_base_image')->setImageFile($product->getFile())->getUrl(); ?>

                                <span class="product-image-container" style="width:152px;">
                                    <span class="product-image-wrapper" style="padding-bottom: 125%;">
                                    <img class="product-image-photo" src="<?=$image_url?>" max-width="152" max-height="190" alt="Erica Evercool Sports Bra"></span>
                                </span>
                            </a>

                            <div class="product details product-item-details">

                                <strong class="product name product-item-name">
                                    <a class="product-item-link" title="<?= $product->getData("name") ?>" href="<?= $product->getProductUrl() ?>">
                                        <?= $product->getData("name") ?>
                                    </a>
                                </strong>

                                <div class="price-box price-final_price" data-role="priceBox" data-product-id="1562" data-price-box="product-id-1562">
                                
                                <span class="normal-price">
                                    <span class="price-container price-final_price tax weee">
                                        <span class="price-label">As low as</span>
                                        <span id="product-price-1562" data-price-amount="22" data-price-type="finalPrice" class="price-wrapper ">
                                            <span class="price">Rp<?= $product->getData("price") ?></span>
                                        </span>
                                    </span>
                                </span>

                                <br/><br/>

                                <span style="width:100%;text-align:center">150 Sold</span>

                                </div>

                            </div>

                        </div>
                    </li>

                <?php endforeach; ?>

            </ol>
        </div>
    </div>
</div>