<?php 
    $_objectManager = \Magento\Framework\App\ObjectManager::getInstance();
    $imageHelper  = $_objectManager->get('\Magento\Catalog\Helper\Image');

    // Currency
    $objectManager = \Magento\Framework\App\ObjectManager::getInstance();
    $currencysymbol = $objectManager->get('Magento\Store\Model\StoreManagerInterface');
    $currency = $currencysymbol->getStore()->getCurrentCurrencyCode();
?>

<div class="block related" style="float: right;width:32%">
    <div class="block-title title">
        <strong id="block-related-heading" role="heading" aria-level="2">
            <h2 style="font-weight:bold;">BEST SELLERS &nbsp;</h2> 
        </strong>
    </div>
    
    <hr />

    <ul style="list-style-type: none;">
        <?php
        $i = 1; 
        foreach ($block->getProducts() as $product): ?>
            <li style="margin-top: 0px;">
                <div>
                    <a class="product-item-link" title="<?= $product->getData("name") ?>" href="<?= $product->getProductUrl() ?>" style="color:grey;">
                        <span style="float: left;font-weight:bold;font-size:25px;">#<?= $i ?> &nbsp;</span>
                        <div style="float: left">
                            <?php echo $product->getData("name") ?><br/>
                            <?php echo $currency ?>. <?php echo $product->getData("price") ?>
                        </div>

                        <div style="float: right;">
                            <?php $image_url = $imageHelper->init($product, 'product_page_image_small')->setImageFile($product->getFile())->resize(100, 55)->getUrl(); ?>
                            <img src="<?=$image_url?>" />   
                        </div>

                        <div style="clear:both"></div>
                    </a>
                </div>
            </li>
        <?php 
        $i++;
        endforeach; ?>
    </ul>


</div>

<div class="block related" style="float: left; width:64%">

    <div class="block-title title">
        <strong id="block-related-heading" role="heading" aria-level="2">
            <h2 style="font-weight:bold;">NEW ARRIVALS &nbsp;</h2> 
        </strong>
    </div>
    <hr />
    <div class="block-content content" aria-labelledby="block-related-heading">

        <div class="products wrapper grid products-grid products-related">
            <ol class="products list items product-items">

                <?php foreach ($block->getProducts() as $product): ?>
                    <li class="item product product-item" style="">
                        <div class="product-item-info">
                            

                            <a href="<?= $product->getProductUrl() ?>" class="product photo product-item-photo">
                                <?php $image_url = $imageHelper->init($product, 'product_base_image')->setImageFile($product->getFile())->getUrl(); ?>

                                <span class="product-image-container" style="width:152px;">
                                    <span class="product-image-wrapper" style="padding-bottom: 125%;">
                                        <span style="float:right; background-color: grey;color:white;padding:1px;">new</span>
                                        <img class="product-image-photo" src="<?=$image_url?>" max-width="152" max-height="190" alt="Erica Evercool Sports Bra">
                                    </span>
                                </span>
                            </a>

                            <div class="product details product-item-details">

                                <strong class="product name product-item-name">
                                    <a class="product-item-link" title="<?= $product->getData("name") ?>" href="<?= $product->getProductUrl() ?>">
                                        <?= $product->getData("name") ?>
                                    </a>
                                </strong>

                                <div class="price-box price-final_price" data-role="priceBox" data-product-id="1562" data-price-box="product-id-1562">
                                    <span class="normal-price">
                                        <span class="price-container price-final_price tax weee">
                                            <span id="product-price-1562" data-price-amount="22" data-price-type="finalPrice" class="price-wrapper ">
                                                <span class="price"> <?php echo $currency ?>.<?= $product->getData("price") ?></span>
                                            </span>
                                        </span>
                                    </span>
                                </div>
                            </div>
                        </div>
                    </li>

                <?php endforeach; ?>

            </ol>
        </div>
    </div>
</div>
<div style="clear:both"></div>