<div>
    <div class="owl-carousel owl-theme"  style="max-width:600px;">
        <div class="item">
            <img src="<?php echo $block->getViewFileUrl('images/slider/banner1.png');?>" />
        </div>

        <div class="item">
            <img src="<?php echo $block->getViewFileUrl('images/slider/banner2.jpg');?>" />
        </div>

        <div class="item">
            <img src="<?php echo $block->getViewFileUrl('images/slider/banner3.jpg');?>" />
        </div>
    </div>
<div>

<script>
    require(['jquery', 'owlcarousel'], function($){
        $('.owl-carousel').owlCarousel({
            rtl:true,
            loop:true,
            margin:10,
            nav:true,
            responsive:{
                0:{
                    items:1
                },
                600:{
                    items:1
                },
                1000:{
                    items:1
                }
            }
        });

        // $("ul.compare").remove();
    })
</script>