<?php

    $objectManager = \Magento\Framework\App\ObjectManager::getInstance(); // Instance of Object Manager
    $categoryFactory = $objectManager->get('\Magento\Catalog\Model\CategoryFactory');// Instance of Category Model
    $categoryId = 15; // YOUR CATEGORY ID
    $category = $categoryFactory->create()->load($categoryId);
    // Parent Categories
    $parentCategories = $category->getParentCategories();
    // Children  Categories
    $childrenCategories = $category->getChildrenCategories();

    foreach ($childrenCategories as $item){
        $parentCategories->addElem($item);
    }

    $_objectManager = \Magento\Framework\App\ObjectManager::getInstance();
    $imageHelper  = $_objectManager->get('\Magento\Catalog\Helper\Image');
?>

<div class="block related">

    <div class="block-title title">
        <strong id="block-related-heading" role="heading" aria-level="2">
            <h2 style="float:left;font-weight:bold;">Top Categories &nbsp;</h2> 
        </strong>
        <hr style="clear:both"/>
    </div>

    <div class="block-content content" aria-labelledby="block-related-heading">
        <div class="products wrapper grid products-grid products-related">
            <ol class="products list items product-items">

                <?php foreach ($parentCategories as $category): ?>

                    <li class="item product product-item" style="">
                        <div class="product-item-info">

                            <a href="#" class="product photo product-item-photo">
                                <img src="<?php echo $block->getViewFileUrl('images/unknown.png');?>"/>
                            </a>

                            <div class="product details product-item-details">

                                <strong class="product name product-item-name">
                                    <a class="product-item-link" title="" href="#">
                                        <?= $category->getData("name") ?>
                                    </a>
                                </strong>

                                <div class="price-box price-final_price" data-role="priceBox" data-product-id="1562" data-price-box="product-id-1562">
                                

                                </div>

                            </div>

                        </div>
                    </li>

                <?php endforeach; ?>

            </ol>
        </div>
    </div>
</div>