<div style="float: left; color:white">
    <h5 style="padding:0px;">ask</h5>
    <h2 style="font-weight: bold">SENHENG</h2>
    <p>
    If you ever need help, or simply have some <br/>suggestions for us, please tell us:
    </p>

    <h3> <img src="<?php echo $block->getViewFileUrl('images/phone.png');?>"/> 03-9281 4040</h3>
    Mon to Fri  |  9.30 am - 5.30 pm <br/>
    (Excluded Public Holiday)

    <h3> <img src="<?php echo $block->getViewFileUrl('images/chat.png');?>"/> Quick Chat</h3>
    Everyday  |  11 am - 10 pm <br/>
    Download Senheng Quick Chat app:
</div>