<div style="float: right; width:250px">
    <h5>WE ACCEPT</h5>
    <img src="<?php echo $block->getViewFileUrl('images/visa.png');?>"/>
    <img src="<?php echo $block->getViewFileUrl('images/mastercard.png');?>" />
    <img src="<?php echo $block->getViewFileUrl('images/ae.png');?>" />
    <img src="<?php echo $block->getViewFileUrl('images/fpx.png');?>" style="width:50px" />
    <img src="<?php echo $block->getViewFileUrl('images/paypal.png');?>" />

    <h5>AVAILABLE INSTALMENTS</h5>
    <img src="<?php echo $block->getViewFileUrl('images/a.png');?>" style="width:50px"/>
    <img src="<?php echo $block->getViewFileUrl('images/b.png');?>" style="width:50px"/>
    <img src="<?php echo $block->getViewFileUrl('images/c.png');?>" style="width:50px"/>
    <img src="<?php echo $block->getViewFileUrl('images/d.png');?>" style="width:50px"/>
    <img src="<?php echo $block->getViewFileUrl('images/e.png');?>" style="width:50px"/>
    <img src="<?php echo $block->getViewFileUrl('images/f.png');?>" style="width:50px"/>

    <h5>FIND US ON!</h5>
    <img src="<?php echo $block->getViewFileUrl('images/instagram.png');?>" />
    <img src="<?php echo $block->getViewFileUrl('images/facebook.png');?>" />
    <img src="<?php echo $block->getViewFileUrl('images/tweeter.png');?>" />
    <img src="<?php echo $block->getViewFileUrl('images/youtube.png');?>" />

</div>