<style>
li > a {
    color:white;
}

ul  li  {
    margin-top: 200px;
}
</style>
<div style="float: left;margin-left:15px;color:white">
    <h5>GENERAL INFO</h5>
    <ul>
        <li><a href="#">About Us</a></li>

        <li><a href="#">Contact Us</a></li>

        <li><a href="#">Careers</a></li>

        <li><a href="#">FAQ</a></li>

        <li><a href="#">Find Nearest Store</a></li>

        <li><a href="#">Privacy Notice</a></li>

        <li><a href="#">Terms of Use</a></li>

        <li><a href="#">Gift Card</a></li>

        <li><a href="#">PlusOne Membership</a></li>
    </ul>
</div>

<div style="float: left;margin-left:15px;color:white">
    <h5>SERVICE</h5>
    <ul>
        <li><a href="#">PlusOne Warranty</a></li>

        <li><a href="#">Standard Installation</a></li>

        <li><a href="#">1-to-1 Replacement Warranty</a></li>

        <li><a href="#">V-Care Extended</a></li>

        <li><a href="#">Insurance</a></li>

        <li><a href="#">Trade in Rebate</a></li>

        <li><a href="#">Order Tracking</a></li>

        <li><a href="#">Return & Refund</a></li>

        <li><a href="#">Order Cancellation</a></li>
    </ul>
</div>