<div style="float: left;width:100%;color:white" >

    <div style="float: left;width:25%;">
        

        <table>
            <tr>
                <td><img style="min-width:50px;" src="<?php echo $block->getViewFileUrl('images/box.png');?>"/></td>
                <td><strong>Next Day Pickup</strong><p>Pickup at your preferred Senheng outlet next day</p></td>
            </tr>
        </table>

    </div>

    <div style="float: left;width:25%;margin-left:15px;">
        

        <table>
            <tr>
                <td><img style="min-width:50px;" src="<?php echo $block->getViewFileUrl('images/box.png');?>"/></td>
                <td><strong>Stores Walk-In Service</strong><p>Fix your broken products at all Senheng stores</p></td>
            </tr>
        </table>
    </div>

    <div style="float: right;width:25%; margin-left:15px;">
    
        <table>
            <tr>
                <td><img style="min-width:50px;" src="<?php echo $block->getViewFileUrl('images/box.png');?>"/></td>
                <td><strong>Zero Interest</strong><p>Long instalment period up to 36 months</p></td>
            </tr>
        </table>
        
    </div>

    <div style="float: right;width:20%;">
        

        <table>
            <tr>
                <td><img style="min-width:50px;" src="<?php echo $block->getViewFileUrl('images/box.png');?>"/></td>
                <td><strong>Free Shipping</strong><p>By purchasing up to RM500 in a single order</p></td>
            </tr>
        </table>
        
    </div>
    
</div>
<hr style="width: 100%;"/>