<div style="float: left">
    <h2>Categories</h2>

    <div class="row">
        <div class="col-md-2" style="float: left">
            <ul>
                <?php foreach ($block->getCategoryCollection() as $k=>$category): ?>
                    <li class="ui-menu-item"><a href="#"><?php echo $category->getName() ?></a></li>

                    <?php if ($k % 15 == 0): ?>
                        </ul>
                        </div>

                        <div style="float: left">
                        <ul>
                    <?php endif ?>
                    
                <?php endforeach; ?>
            </ul>
        </div>
    </div>
</div>