<nav class="navigation" data-action="navigation" style="text-align: center; background-color:white;">
    <ul id="menu" data-mage-init='{"menu":{"responsive":true, "expanded":true, "delay": 200, "position":{"my":"left top","at":"left+10 top+30"}}}'>        
        <li class="level0 level-top parent ui-menu-item">Categories
            <ul class="level0 submenu ui-menu ui-widget ui-widget-content ui-corner-all" style="text-align: left;">
                <?php foreach ($block->getCategoryCollection() as $category): ?>
                    <li class="ui-menu-item"><a href="#"><?php echo $category->getName() ?></a></li>
                <?php endforeach; ?>
            </ul>
        </li>
        <li class="level0 level-top ui-menu-item">About</li>
        <li class="level0 level-top ui-menu-item">Contact</li>
    </ul>
</nav>